### ISSUE TITLE
make: *** [Makefile: 7 install] Error 1

### ISSUE THREAD

**Issue by darwinlatorre** [anaysharma/nibar-plymouth-theme#2]
Well, i was trying to instal the plymouth themes, but i got this error.

`$] sudo make install`
`mkdir -p /usr/share/plymouth/themes`
`cp -r numix /usr/share/plymouth/themes`
`cp: cannot stat 'numix': No such file or directory`
`make: *** [Makefile:7: install] Error 1 `

I dont know  if its my error, if it's what i can do?

**Comment by anaysharma** [comment]
Sorry for being late, some stuff came up

Replace numix with nibar.
Thank you

**Comment by anaysharma** [comment]
Its fixed now.
Thank you for issue.

Sorry for being late, some stuff came up.
